### ISSUE TITLE
[新機能]: スキルセットをyamlで保存

### ISSUE THREAD

**Issue by Koryu25** [eryuLab/SkillMaster#256]
### 具体的な提案内容

スキルセットとは、右クリック、スワップ、ドロップキーの１、２、３番に登録されているスキル群のことをいう  
プレイヤーはスキルセットを合計で５つ保持できる。  
一つは実際に使う現在のスキルセット、残りの４つは特定のスキルセットに瞬時に変更するための枠としてのスキルセット  
### yaml設計
``` yaml
skillset:
    Koryu25:
        current:
            r1: okigiri
            r2: kazagiri
            r3: wall
            s1: slapstep
            s2: razorstab
            s3:
            d1:
            d2:
            d3:
        '1': 
            r1: okigiri
            r2: kazagiri
            r3: wall
            s1: slapstep
            s2: razorstab
            s3:
            d1:
            d2:
            d3:
        '2': ...
```

### 想定されるコード

N/A
